### PR TITLE
Update

### PR DESCRIPTION
**Pull request by gakada**

### CODE REVIEW

**Comment by gakada** [comment]
@KagamiChan this needs updating.

Though there are also some quests issues, e.g., in CSV:

```csv
235,【節分任務】鎮守府海域 南西方面防衛作戦
```

But in JSON:

```json
    "game_id": 235,
    "name": "近海哨戒を実施せよ!",
```

**Comment by KagamiChan** [comment]
Sorry for forgetting this thread

will take a look

**Comment by KagamiChan** [comment]
The issue

- poi db's quest record data gets corrupted somehow, the reason might be falsy reports or some Tanaka tricks
- I chose to use that because it is the original source from game API, other records Wikia or kcwiki, may not match the text in some way

Given this I have to hold the quest name updates unless we change to a good way to record quests

btw, does tsundb have the quest name collection?

**Comment by KagamiChan** [comment]
also this may be the problem from kcwiki data as the relationship between wiki numbering and API numbering is maintained there

Do we have alternative source for that?

**Comment by lawvs** [comment]
Just for convenience, [kcdata/quest](https://github.com/kcwikizh/kcdata/tree/gh-pages/quest) uses [kc3-translations](https://github.com/KC3Kai/kc3-translations/blob/master/data/jp/quests.json) as the game_id data source now. ([poi db's quest record data](https://poi.0u0.moe/dump/quests.csv.gz) need to decompress).

In theory, the data of KC3 should have consistent data with poi db, I want to know which data is correct.

**Comment by KagamiChan** [comment]
Thanks @lawvs 

That's a good source, we can see that for id 235, there're 235 and (legacy) 235SB38, seems 235SB38 came first, thus the new 235 should override it

**Comment by KagamiChan** [comment]
So I think kcwiki data is correct, it's poi db's collection strategy should change

**Pull request merged**
